## 파이토치
- 페이스북 주도로 여러 회사와 대학이 합심해 개발한 오픈소스 프로젝트
- 2016년 8월 첫 공개

### vs Numpy
- 파이토치는 backward()라는 함수를 통해 그래프 연산 한번에
- GPU 연산 가능 (GPU로 값을 보내 연산을 돌리고 다시 받는 것이 불가능)
- 내부적인 CUDA, CUDNN API를 통해 GPU 연산에 사용 가능

### vs Tensorflow
#### 1. 텐서플로
- 그래프를 미리 정해두고 실행중에는 바꿀 수 없음 (정적 계산 그래프 static computational graph) 방식
- 정적 계산 그래프 방식은 그래프 계산 방식을 최초에 정해두기 때문에 최적화하기가 쉬움
- 정적인 데이터셋 학습 및 정적인 모델 배포 -> 오프라인 학습(offline learning)

#### 2. 파이토치
- 동적 계산 그래프 방식 (dynamic computational graph)
- 데이터에 대해 유연한 모델을 만들 수 있음
- 자율주행차, 게임, 인터넷 등 쌓이는 데이터에 대한 실시간 대응하는 동적인 학습 방법이 중요해질 전망

### 파이토치 라이브러리
- Torchvision : 각종 비전 및 데이터 관리용 도구
- TorchText : 각종 텍스트 데이터셋 및 데이터 관리용 도구

### 파이토치 API
- torch.nn
- torch.optim as optim : 경사하강법 알고리즘들
- torch.nn.init : 텐서 초깃값 함수들

<hr>

## Torchvision Dataset

- Face
    - CelebA (얼굴데이터셋)
    
- Image Classification
    - CIFAR (사물 데이터셋)
    - ImageNet
    - MNIST
        - EMNIST(알파벳 + 숫자)
        - Fashion-MNIST
        - KMNIST(고대 중세 일본문자)
        - QMNIST
    - LSUN (Scene classification)
- Segmentation
    - Cityscapes(도시 길거리 데이터셋, segmentation용),
- Object Detection
    - COCO, VOC (Captioning and Detection)
- Image Description
    - Flickr
- Etc
    - FakeData(Random Noise Data)
    - HMDB51 (action classification dataset)
    - Kinetics-400 / Omniglot / PhotoTour / Places365
    - SBD / SBU / STL10 / SVHN / UCF101 / USPS

<hr>

## 1. Torch Tensor
- torch는 numpy와 거의 비슷
- torch.Tensor(data, dtype, device, requires_grad)
- device : cpu, gpu / requires_grad : 미분값 저장 여부 (default : false)
- **torch.no_grad() : 테스트 모드 (기울기 안구하는)**
    - dropout 등의 작동안하기 때문에 속도가 좀더 빠름

In [15]:
import torch
import numpy as np
t = torch.tensor(data = [[1,2],[3,4]], dtype = torch.float64, device = 'cpu', requires_grad = True)
t

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64, requires_grad=True)

#### arange, numpy(), reshape, broadcasting

In [16]:
s = torch.arange(9)
print(s, s.shape, s.numpy())
print(s.reshape(3,3))
print(s*3, s+s ) # broadcasting 가능

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([9]) [0 1 2 3 4 5 6 7 8]
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24]) tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])


#### randn, zeros, ones, zeros_like

In [17]:
randoms = torch.rand((2,2))
zeros = torch.zeros((2,2))
ones = torch.ones((2,2))
zeros_like = torch.zeros_like(ones) # 닮고 싶은 matrix 
print(randoms, '\n', zeros, '\n', ones, '\n', zeros_like)

tensor([[0.5332, 0.8513],
        [0.1716, 0.0839]]) 
 tensor([[0., 0.],
        [0., 0.]]) 
 tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0., 0.],
        [0., 0.]])


#### add, view, from_numpy()

In [18]:
print(torch.add(ones, 5))
print(ones.view(-1)) 
print(torch.from_numpy(np.array([4,1,5])))

tensor([[6., 6.],
        [6., 6.]])
tensor([1., 1., 1., 1.])
tensor([4, 1, 5], dtype=torch.int32)


<hr>

## 2. Torch Tensor Processing
- 텐서의 원소수는 유지하되 모양과 차원을 조절
- squeeze(), unsqueeze()
- view() : 데이터 reshape

In [11]:
import torch

x = torch.tensor([[1,2,3],[10,11,12]])
print('데이터:', x, '데이터 size:', x.size(), '데이터 shape:', x.shape, '데이터 차원:', x.ndimension(), '\n')

# 랭크 늘리기
x = torch.unsqueeze(x,0)
print('랭크늘리기')
print('데이터:', x, '데이터 size:', x.size(), '데이터 shape:', x.shape, '데이터 차원:', x.ndimension(), '\n')

# 텐서 줄이기
x = torch.squeeze(x)
print('랭크줄이기')
print('데이터:', x, '데이터 size:', x.size(), '데이터 shape:', x.shape, '데이터 차원:', x.ndimension(), '\n')

# view 함수 = reahpe역할
x = x.view([3,2])
print('view(reshape')
print('데이터:', x, '데이터 size:', x.size(), '데이터 shape:', x.shape, '데이터 차원:', x.ndimension(), '\n')


데이터: tensor([[ 1,  2,  3],
        [10, 11, 12]]) 데이터 size: torch.Size([2, 3]) 데이터 shape: torch.Size([2, 3]) 데이터 차원: 2 

랭크늘리기
데이터: tensor([[[ 1,  2,  3],
         [10, 11, 12]]]) 데이터 size: torch.Size([1, 2, 3]) 데이터 shape: torch.Size([1, 2, 3]) 데이터 차원: 3 

랭크줄이기
데이터: tensor([[ 1,  2,  3],
        [10, 11, 12]]) 데이터 size: torch.Size([2, 3]) 데이터 shape: torch.Size([2, 3]) 데이터 차원: 2 

view(reshape
데이터: tensor([[ 1,  2],
        [ 3, 10],
        [11, 12]]) 데이터 size: torch.Size([3, 2]) 데이터 shape: torch.Size([3, 2]) 데이터 차원: 2 



## 3. Torch Tensor multiplication

In [13]:
w = torch.randn(2,3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0,4.0], [5.0,6.0]]) # 3,2
print('w\n', w,'\n x \n', x)

b = torch.randint(-1, 1, (2,2))
print('b\n', b)

wx = torch.mm(w,x)
print('wx\n', wx)

result = wx+b
print('result\n', result)

w
 tensor([[-0.9356,  0.8518,  1.4608],
        [ 0.2092, -0.2177, -0.1555]]) 
 x 
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
b
 tensor([[ 0, -1],
        [ 0,  0]])
wx
 tensor([[ 8.9240, 10.3011],
        [-1.2215, -1.3855]])
result
 tensor([[ 8.9240,  9.3011],
        [-1.2215, -1.3855]])


<hr>

## 4. Torch.backward()
- 오차를 수학 함수로 표현 한 후 미분하여 이 함수의 기울기를 구해 오차의 최소값이 있는 방향을 찾아내는 알고리즘

In [47]:
w = torch.tensor([2.0], requires_grad = True)
w2 = torch.tensor([3.0], requires_grad=True)
print('기본 tensor', w, w2)

# 미분1
loss = 2*(w**2) + 2*w + 7 # 2w^2 + 2w + 7 
print('연산 그래프 계산 한 값 {}'.format(loss))

loss.backward() # ==> 4w + 2
print('w로 미분한 값(a)은 {}'.format(w.grad))

# 미분2
loss2 = 3*(w2**2) + 3*w2 + 7 # 3w^2 + 3w + 7 
loss2.backward() # ==> 6w + 3

print('w로 미분한 값(a)은 {}'.format(w2.grad))

기본 tensor tensor([2.], requires_grad=True) tensor([3.], requires_grad=True)
연산 그래프 계산 한 값 tensor([19.], grad_fn=<AddBackward0>)
w로 미분한 값(a)은 tensor([10.])
w로 미분한 값(a)은 tensor([21.])


## 5.Torch.optim
- 경사하강법을 적용한 오차를 줄이고 최적의 가중치와 편차를 근사
- SGD :Stochatstic gradient descent, 한 번에 들어오는 데이터의 수대로 경사하강법 알고리즘을 적용
- Linear Regression Model에서의 L1Loss와 SGD Optimizer를 사용

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init # 텐서 초깃값 주기 위한 함수들

num_data = 100
num_epoch = 500

# (1) Define X, y, noise Tensor
x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
y = 2*x + 3

noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y_noise = y+noise

# (2) 선형 회귀 모델, loss, optimizer 정의
model = nn.Linear(1,1) # (1개 x를 넣어서 1개의 y가 나오는) 
loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(), lr=0.01) # model의 parameters에 대해서 최적화 하겠다는 것

# 정답
label = y_noise

print('Model:', model)
print('Model.parameters : ', model.parameters)
print('x, y, y_noise, shape', x.shape, y.shape, y_noise.shape)


C:\Users\urse\Anaconda3\envs\seonmin\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\urse\Anaconda3\envs\seonmin\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\urse\Anaconda3\envs\seonmin\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


Model: Linear(in_features=1, out_features=1, bias=True)
Model.parameters :  <bound method Module.parameters of Linear(in_features=1, out_features=1, bias=True)>
x, y, y_noise, shape torch.Size([100, 1]) torch.Size([100, 1]) torch.Size([100, 1])


In [59]:
# 순서
## (1) zero_gard() 기울기 초기화
## (2) model 결과 output 추출
## (3) y_true, y_pred간의 loss추출
## (4) loss.backward()로 loss 전파
## (5) optimizer.step() 실제 가중치 반영 (model.parameters()에 리턴되는 변수들의 기울기에 학습률 곱하고 빼줌)
## (6) 처음 유도했던 Tensor 2와 3 에 가깝게 나옴.
for i in range(num_epoch):
    optimizer.zero_grad() # 지난번 계산했던 기울기 초기화 (0으로)
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i%100 == 0:
        print(loss.data)
        param_list = list(model.parameters())
        print(param_list[0].item(), param_list[1].item())

tensor(0.8165)
1.9748817682266235 2.8977646827697754
tensor(0.8146)
1.9764351844787598 2.9357707500457764
tensor(0.8148)
1.9765570163726807 2.9413716793060303
tensor(0.8145)
1.9752084016799927 2.941971778869629
tensor(0.8146)
1.975310206413269 2.941971778869629
