In [1]:
import tensorflow as tf
import numpy as np

# Tensor 생성
## list -> tensor
## tuple -> tensor
## array -> tensor
a = tf.constant([1,2,3])
b = tf.constant(((1,2,3),(4,5,6)))
c = tf.constant(np.array([[1,2,3],[4,5,6],[7,8,9]]))

In [2]:
a

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [3]:
b

<tf.Tensor: id=1, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
c

<tf.Tensor: id=2, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [5]:
# dtype을 미리 정해주거나
# tf.cast 을 통해서 변환 가능 ( = np.astype 과 같은것)
d = tf.constant([[1,2,3,4],[5,6,7,8]], dtype=tf.float64)
print(d)
print(tf.cast(d , dtype=tf.uint8))

tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float64)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=uint8)


In [6]:
# 난수 생성 방법 2가지
# (1) uniform distribution - 중심극한 이론에 의한 연속적인 모양
# (2) normal distribution - 중심극한이론과는 무관, 불연속적이며 일정한 분포

# 가중치 일반적으로 초기화할떄 random 많이 씀
# numpy에서는 np.random.randn()
# tensorflow 에서는 tf.random.normal

print(np.random.randn(9))
print(tf.random.normal([3,3])) # 중심 극한정리적으로 생성
print(tf.random.uniform([3,3])) # 중심극한정리x 맘대로생성


[-0.50690588 -0.30184216 -0.59688202  0.27874861  0.48228965 -0.76257444
  1.14548709  1.44478691 -2.72444493]
tf.Tensor(
[[-3.1300404   1.0205297   0.50603086]
 [ 0.86770856 -0.5073489   0.772137  ]
 [-1.2822214  -1.2957399   1.360654  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.23422503 0.9709836  0.962252  ]
 [0.58332586 0.2049948  0.05581009]
 [0.81179404 0.04408777 0.70823014]], shape=(3, 3), dtype=float32)
