## Tensorflow 2.0 연습

In [20]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.0.0


## 1. Defining Tensors

In [3]:
m1 = [[1.0, 2.0], [3.0, 4.0]]
m2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(type(m1), type(m2), type(m3))

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3 , dtype=tf.float32)
print(type(t1), type(t2), type(t3)) 

# eager mode 이기 때문에 바로 print 로 출력가능 (1.0 버전과 다른 것)
print(t1)


<class 'list'> <class 'numpy.ndarray'> <class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
# np.array 와 tensor type 과는 거의 연동됨.

ndarray = np.ones([3,3])

tensor = tf.multiply(ndarray, 42)
print(tensor)

# np 전체에다가 1 더하기
print(np.add(tensor, 1))

# tensor to numpy
print(type(tensor.numpy()))

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
<class 'numpy.ndarray'>


In [6]:
# tf. constant

a = tf.constant(1.5)
b = tf.constant(2.5) 

# numpy() 라고 붙이면 그냥 값만, 전체 출력시도 가능
print(a.numpy())
print(b)

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


## 2. Operations

In [8]:
# 덧셈과 곱셈
a_plus_b = tf.add(a,b)
print(a_plus_b)

a_mul_b = tf.multiply(a,b)
print(a_mul_b)

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(3.75, shape=(), dtype=float32)


## 3. Variables 
- placeholder 는 없어짐

In [9]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5,2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[-0.0204947 ,  0.04981499],
       [-0.02288328, -0.15046576],
       [ 0.00838564,  0.06883458],
       [ 0.10868975, -0.10922921],
       [ 0.06711064,  0.06097421]], dtype=float32)>


## 4. Create Dataset
- Preprocessing 할 떄 편한 것
- iterate 시 비복원추출로 진행 batch가 2이면 2개씩 모~든걸 다뽑을떄까지 진행되는 것
- ds_tensor.take(2) -> 2회만 진행

In [15]:
a = np.arange(10)
ds_tensors = tf.data.Dataset.from_tensor_slices(a)
print(ds_tensors)

## apply transformations -  한 에폭이 지나갈 때마다 셔플여부, 20은 몇개를 바꿀건지
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)
print(ds_tensors)

<TensorSliceDataset shapes: (), types: tf.int32>
<BatchDataset shapes: (None,), types: tf.int32>


In [19]:
# 데이터를 공급하는 것
# iterate

print('Elements of ds_tensors:')
for _ in range(3): # 3 epoch이라고 생각
    for x in ds_tensors: # batch 로 돌아감 (2라고 설정하면 2개씩 돌아감) 
        print(x, '\n')

Elements of ds_tensors:
tf.Tensor([36 64], shape=(2,), dtype=int32) 

tf.Tensor([ 0 81], shape=(2,), dtype=int32) 

tf.Tensor([49  1], shape=(2,), dtype=int32) 

tf.Tensor([ 9 25], shape=(2,), dtype=int32) 

tf.Tensor([16  4], shape=(2,), dtype=int32) 

tf.Tensor([64 36], shape=(2,), dtype=int32) 

tf.Tensor([81 16], shape=(2,), dtype=int32) 

tf.Tensor([ 1 49], shape=(2,), dtype=int32) 

tf.Tensor([25  0], shape=(2,), dtype=int32) 

tf.Tensor([4 9], shape=(2,), dtype=int32) 

tf.Tensor([81 49], shape=(2,), dtype=int32) 

tf.Tensor([ 9 16], shape=(2,), dtype=int32) 

tf.Tensor([25  0], shape=(2,), dtype=int32) 

tf.Tensor([ 1 36], shape=(2,), dtype=int32) 

tf.Tensor([64  4], shape=(2,), dtype=int32) 



In [17]:
# 데이터를 공급하는 것
# iterate

print('Elements of ds_tensors:')
for _ in range(3): # 3 epoch이라고 생각
    for x in ds_tensors.take(2): # 2번만 가져옴 
        print(x)

Elements of ds_tensors:
tf.Tensor([25  0], shape=(2,), dtype=int32)
tf.Tensor([16 49], shape=(2,), dtype=int32)
tf.Tensor([ 4 16], shape=(2,), dtype=int32)
tf.Tensor([ 0 25], shape=(2,), dtype=int32)
tf.Tensor([16 64], shape=(2,), dtype=int32)
tf.Tensor([25  0], shape=(2,), dtype=int32)
