## Tensorflow 2.0 연습
- EagerMode로 변환된 Tensorflow 2.0 -> 바로바로 변수 print출력 가능

In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.0.0


## 1. Defining Tensors
- tf.constant (변할 수 없는 상수)
    - 상수형 tensor를 생성하는 방법은 ones, zeros 를 생성하는 방법
- tf.variables (변할수 있는 상수) - 변수

In [2]:
m1 = [[1.0, 2.0], [3.0, 4.0]]
m2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(type(m1), type(m2), type(m3))

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3 , dtype=tf.float32)
print(type(t1), type(t2), type(t3)) 

# eager mode 이기 때문에 바로 print 로 출력가능 (1.0 버전과 다른 것)
print(t1)


<class 'list'> <class 'numpy.ndarray'> <class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [3]:
# np.array 와 tensor type 과는 거의 연동됨.

ndarray = np.ones([3,3])*2
ndarray2 = np.ones([3,3])*3

print('ndarray1\n', ndarray)
print('ndarray2\n', ndarray2)

ndarray1
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
ndarray2
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [4]:
# tf. constant

a = tf.constant(1.5)
b = tf.constant(2.5) 

# numpy() 라고 붙이면 그냥 값만, 전체 출력시도 가능
print(a.numpy())
print(b)

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


In [5]:
# tf.Variable

weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5,2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.03219075, -0.08574013],
       [-0.13154219, -0.10443261],
       [ 0.02964348,  0.02962355],
       [-0.02480943, -0.02048242],
       [-0.16413125, -0.01223512]], dtype=float32)>


## 2. TF tensor 사칙연산 (Operations)

In [6]:
# tf.multiply -> 각 tensor 원소끼리 곱하기
tensor = tf.multiply(ndarray, 7)
print(tensor)

# tf.multiply 각 tensor 원소끼리 그대로 곱하기
tensor = tf.multiply(ndarray, ndarray2)
print(tensor)

# tf.matmul 행렬 곱 하기
tensor = tf.matmul(ndarray, ndarray2)
print(tensor)

tf.Tensor(
[[14. 14. 14.]
 [14. 14. 14.]
 [14. 14. 14.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]], shape=(3, 3), dtype=float64)


In [17]:
# np 전체에다가 1 더하기
print(tf.add(tensor, 1))

# tensor 전체에다가 1 마이너스
print(tf.subtract(tensor, 2))

# 루트 연산 적용하는 것.
print(tf.sqrt(tensor))

# 제곱연산
print(tf.square(tensor))

# tensor to numpy - tensor.numpy() 함수 하면 됨.
print(type(tensor.numpy()))

tf.Tensor(
[[19. 19. 19.]
 [19. 19. 19.]
 [19. 19. 19.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[16. 16. 16.]
 [16. 16. 16.]
 [16. 16. 16.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[4.24264069 4.24264069 4.24264069]
 [4.24264069 4.24264069 4.24264069]
 [4.24264069 4.24264069 4.24264069]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[324. 324. 324.]
 [324. 324. 324.]
 [324. 324. 324.]], shape=(3, 3), dtype=float64)
<class 'numpy.ndarray'>


## 3. TF.Variable 에 값 할당, 더해주기
- assign : 단순 할당
- assign_add : 원래 값에 (값) 더해주는 것
- assign_sub : 원래 값에 (값) 빼주는 것

In [13]:
# Varialbe 변수 생성
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

# Variable에 값 할당 // 할시 assign / assign_add / assign_sub
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.77083355, -0.79851013],
       [-0.51751125,  1.1656736 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.7720935 ,  0.26149568],
       [-0.48295823,  0.19856483]], dtype=float32)>


In [14]:
# 더해줄 값
added_value = np.array([[10,10],[10,10]])

print('원본 함수')
print(a)

print('assign_add 함수')
a.assign_add(added_value)
print(a)

원본 함수
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.7720935 ,  0.26149568],
       [-0.48295823,  0.19856483]], dtype=float32)>
assign_add 함수
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 8.227906, 10.261496],
       [ 9.517042, 10.198565]], dtype=float32)>
