### 1. Matrix
- 행렬(matrix)는 벡터를 원소로 가지는 2차원 배열
- 행(row), 열(column)이라는 인덱스를 가짐
- 같은 모양을 가지면 덧셈, 뺄셈 가능

<hr>

### 2. Matrix Multiplication
- **i번째 행백터와 j번째 열벡터 사이의 내적**을 성분으로 가지는 행렬을 계산
- X의 열 의 갯수와 Y의 행의 갯수가 같아야 계산 가능

- $XY = (∑_k x_ik*y_kj)$

<hr>

In [14]:
import numpy as np

# 일반 행렬 곱
X = np.array([[1,2],[3,4]])
Y = np.array([[4,3],[2,1]])
print(f'x:\n{X}')
print(f'y:\n{Y}')
print(f'X*Y:\n{X.dot(Y)}')

# 내적을 이용한 행렬 곱
# np.inner 함수를 사용하여 계산 하는법
print(f'inner X*Y:\n{np.inner(X, Y.T)}')

x:
[[1 2]
 [3 4]]
y:
[[4 3]
 [2 1]]
X*Y:
[[ 8  5]
 [20 13]]
inner X*Y:
[[ 8  5]
 [20 13]]


## 3. Inverse Matrix
- 어떤 행렬 A의 연산을 거꾸로 되돌리는 행렬을 역행렬(Inverse Matrix)라고 함
- 좌표평면에서의 역행렬이라면 어떤 점들을 행렬식에 의해 다른 점들로 이동하는 경우
- 역행렬은 행과 열 숫자가 같고 행렬식이 0이 아닌 경우(ad-bc)만 계산 가능
- 역행렬을 계산할 수 없다면
    - 유사 역행렬(pseudo-inverse)
    - 무어펜로즈(Moore-Penrose)역행렬 ($A^+)$)


In [22]:
## 역행렬, 유사역행렬
X_INV = np.linalg.inv(X)
print(f'X:\n{X}')
print(f'X_inv:\n{X_INV}') # 유사역행렬
print(f'p_inv:\n{np.linalg.pinv(X)}')
print(f'X*X_INV:\n{X.dot(X_INV)}')


X:
[[1 2]
 [3 4]]
X_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]
p_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]
X*X_INV:
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
