In [88]:
import numpy as np

# padding 만들어주기
def padding(data, num):
    return np.pad(data, ((num,num),(num,num)), 'constant', constant_values=0)

# conv 연산
def conv(data, kernel):
    mok = kernel.shape[0]//2
    result = np.zeros((data.shape[0]-2*mok,data.shape[1]-2*mok))
    for i in range(1*mok, data.shape[0]-1*mok):
        for j in range(1*mok, data.shape[1]-1*mok):
            x = data[i-1*mok:i-1*mok+kernel.shape[0], j-1*mok:j-1*mok+kernel.shape[1]]*kernel
            result[i-1*mok,j-1*mok] = x.sum()
    return result

In [89]:
np.random.seed(10)

x = [np.random.randint(10) for i in range(0,49)]
image = np.array(x).reshape(7,7)
print('image\n', image)

image
 [[9 4 0 1 9 0 1]
 [8 9 0 8 6 4 3]
 [0 4 6 8 1 8 4]
 [1 3 6 5 3 9 6]
 [9 1 9 4 2 6 7]
 [8 8 9 2 0 6 7]
 [8 1 7 1 4 0 8]]


## 3x3 연산 1번, 2번

In [90]:

kernel3 = np.array([[1,0,1],[0,1,0],[1,0,1]])
print('kernel3\n',kernel3)

pad_image1 = padding(image, 1)
print('pad_image1\n',pad_image1)

conv(pad_image1, kernel3)

kernel3
 [[1 0 1]
 [0 1 0]
 [1 0 1]]
pad_image1
 [[0 0 0 0 0 0 0 0 0]
 [0 9 4 0 1 9 0 1 0]
 [0 8 9 0 8 6 4 3 0]
 [0 0 4 6 8 1 8 4 0]
 [0 1 3 6 5 3 9 6 0]
 [0 9 1 9 4 2 6 7 0]
 [0 8 8 9 2 0 6 7 0]
 [0 8 1 7 1 4 0 8 0]
 [0 0 0 0 0 0 0 0 0]]


array([[18., 12., 17.,  7., 21.,  9.,  5.],
       [16., 24., 17., 24., 23., 19., 11.],
       [12., 19., 31., 23., 27., 26., 17.],
       [ 6., 27., 23., 23., 29., 23., 20.],
       [20., 25., 27., 22., 24., 22., 22.],
       [10., 41., 16., 24., 11., 27., 13.],
       [16., 18., 17., 10., 12.,  7., 14.]])

In [93]:
kernel3 = np.array([[1,0,1],[0,1,0],[1,0,1]])
print('kernel3\n',kernel3)

pad_image1 = padding(image, 1)
print('padding 첫번째 \n',pad_image1)

conv1 = conv(pad_image1, kernel3)
print('conv33 첫번째 \n',conv1)

pad2 = padding(conv1, 1)
print('padding 두번째 \n',pad2)

conv2 = conv(pad2, kernel3)
print('conv33 두번째 \n',conv2)


kernel3
 [[1 0 1]
 [0 1 0]
 [1 0 1]]
padding 첫번째 
 [[0 0 0 0 0 0 0 0 0]
 [0 9 4 0 1 9 0 1 0]
 [0 8 9 0 8 6 4 3 0]
 [0 0 4 6 8 1 8 4 0]
 [0 1 3 6 5 3 9 6 0]
 [0 9 1 9 4 2 6 7 0]
 [0 8 8 9 2 0 6 7 0]
 [0 8 1 7 1 4 0 8 0]
 [0 0 0 0 0 0 0 0 0]]
conv33 첫번째 
 [[18. 12. 17.  7. 21.  9.  5.]
 [16. 24. 17. 24. 23. 19. 11.]
 [12. 19. 31. 23. 27. 26. 17.]
 [ 6. 27. 23. 23. 29. 23. 20.]
 [20. 25. 27. 22. 24. 22. 22.]
 [10. 41. 16. 24. 11. 27. 13.]
 [16. 18. 17. 10. 12.  7. 14.]]
padding 두번째 
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 18. 12. 17.  7. 21.  9.  5.  0.]
 [ 0. 16. 24. 17. 24. 23. 19. 11.  0.]
 [ 0. 12. 19. 31. 23. 27. 26. 17.  0.]
 [ 0.  6. 27. 23. 23. 29. 23. 20.  0.]
 [ 0. 20. 25. 27. 22. 24. 22. 22.  0.]
 [ 0. 10. 41. 16. 24. 11. 27. 13.  0.]
 [ 0. 16. 18. 17. 10. 12.  7. 14.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
conv33 두번째 
 [[ 42.  45.  65.  47.  64.  43.  24.]
 [ 47. 102.  78. 120.  88.  89.  46.]
 [ 63.  81. 129. 115. 116. 109.  59.]
 [ 50. 117. 112. 132. 122. 113.  68

## 5x5 컨볼루션 연산

In [76]:
kernel5 = np.array([[1,0,0,0,1],[0,1,0,1,0],[0,0,1,0,0,],[0,1,0,1,0],[1,0,0,0,1]])
print('kernel5\n',kernel5)

pad_image2 = padding(image, 2)
print('pad_image2\n',pad_image2)

conv(pad_image2, kernel5)


kernel5
 [[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]
pad_image2
 [[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 9 4 0 1 9 0 1 0 0]
 [0 0 8 9 0 8 6 4 3 0 0]
 [0 0 0 4 6 8 1 8 4 0 0]
 [0 0 1 3 6 5 3 9 6 0 0]
 [0 0 9 1 9 4 2 6 7 0 0]
 [0 0 8 8 9 2 0 6 7 0 0]
 [0 0 8 1 7 1 4 0 8 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


array([[24., 20., 18., 19., 31., 17.,  6.],
       [22., 29., 21., 36., 35., 24., 14.],
       [21., 24., 60., 34., 44., 31., 28.],
       [15., 37., 45., 50., 48., 33., 26.],
       [33., 34., 40., 35., 49., 31., 27.],
       [16., 46., 20., 36., 23., 32., 16.],
       [25., 22., 28., 17., 28., 11., 16.]])